// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyuTN62zeKVVCnA_2Fl2rX5EoMQejwq6w',
    appId: '1:959070188236:web:44c05b84873afe719c4869',
    messagingSenderId: '959070188236',
    projectId: 'start-of-firebase',
    authDomain: 'start-of-firebase.firebaseapp.com',
    databaseURL: 'https://start-of-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'start-of-firebase.firebasestorage.app',
    measurementId: 'G-04JJD0709P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa9mH7T0n2bq7pJqqpHbwy8MmMSWkAOdE',
    appId: '1:959070188236:android:d0ffe5343321c5a89c4869',
    messagingSenderId: '959070188236',
    projectId: 'start-of-firebase',
    databaseURL: 'https://start-of-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'start-of-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwAO0pJxMaNfHkdd-QtTPtWOGXFerVpNo',
    appId: '1:959070188236:ios:a9ca9e08732faea99c4869',
    messagingSenderId: '959070188236',
    projectId: 'start-of-firebase',
    databaseURL: 'https://start-of-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'start-of-firebase.firebasestorage.app',
    iosClientId: '959070188236-pp4k4bvvpatn3sv2oo4eo5ih4ub5s5ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.muhafiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwAO0pJxMaNfHkdd-QtTPtWOGXFerVpNo',
    appId: '1:959070188236:ios:a9ca9e08732faea99c4869',
    messagingSenderId: '959070188236',
    projectId: 'start-of-firebase',
    databaseURL: 'https://start-of-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'start-of-firebase.firebasestorage.app',
    iosClientId: '959070188236-pp4k4bvvpatn3sv2oo4eo5ih4ub5s5ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.muhafiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyuTN62zeKVVCnA_2Fl2rX5EoMQejwq6w',
    appId: '1:959070188236:web:2de981c0e5bbd9a79c4869',
    messagingSenderId: '959070188236',
    projectId: 'start-of-firebase',
    authDomain: 'start-of-firebase.firebaseapp.com',
    databaseURL: 'https://start-of-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'start-of-firebase.firebasestorage.app',
    measurementId: 'G-14G19DV495',
  );
}
